---
title: "Untitled"
author: "Hao Zheng(hz2772)"
date: "11/11/2021"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(p8105.datasets)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
## Problem 1
```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv", na=c("","Unknown")) %>%
  mutate(
    city_state = str_c(city,state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")
```

```{r}
baltimore_df = 
  homicide_df %>%
  filter(city_state=="BaltimoreMD")

baltimore_summary=
  baltimore_df %>%
    summarise(
      unsolved = sum(resolution == "unsolved"),
      n = n()
    ) 
baltimore_test=
  prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n)
)

baltimore_test %>%
  broom::tidy()
```

```{r}
prop.test_function = function(city_df){
  
  city_summary=
    city_df %>%
    summarise(
        unsolved = sum(resolution == "unsolved"),
        n = n()
      ) 
  city_test=
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n)
    )

  return(city_test)

}

prop.test_function(baltimore_df)
homicide_df %>% 
  filter(city_state=="AlbuquerqueNM") %>%
  prop.test_function()
```

```{r}
results_df = 
  homicide_df %>%
  nest(data = uid:resolution) %>%
  mutate(
    test_results = map(data,prop.test_function),
    tidy_results = map(test_results,broom::tidy)
  ) %>%
  select(city_state,tidy_results) %>%
  unnest(tidy_results) %>%
  select(city_state,estimate,starts_with("conf"))
```

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state,estimate)) %>%
  ggplot(aes(x=city_state,y=estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin=conf.low,ymax=conf.high)) +
  theme(axis.text.x  = element_text(angle = 90,vjust = 0.5,hjust = 1))
```

```{r}
homicide_df %>%
  group_by(city_state) %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n=n()
  )  %>%
  mutate(
    test_results = map2(unsolved,n,prop.test),
    tidy_results = map(test_results,broom::tidy)
  ) %>%
  select(city_state, tidy_results) %>%
  unnest(tidy_results) %>%
  select(city_state,estimate,starts_with("conf"))
```

## Problem 2
```{r}
arm_file =
  tibble(
    files = str_c("./data/zip_data/",list.files("./data/zip_data"))
  ) 

arm_data = 
  arm_file %>%
  mutate(
    subject_id = rep(c(1:10),2),
    type = c(rep("con",10),rep("exp",10)),
    data = purrr::map(files,read.csv)) %>%
  unnest(data) %>%
  select(-files) 

arm_data %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "data"
  ) %>%
  mutate(subject_id=as.factor(subject_id)) %>%
  mutate(category=str_c(subject_id,type)) %>%
  group_by(type) %>%
  ggplot(aes(x=week,y=data,group=category,color=type)) + 
  geom_point() + 
  geom_line(aes(linetype=type)) +
  labs(
    title = "Arm Data Plot",
    x = "Week",
    y = "Arm Data")
```

**A:** According to the plot, it's clear that the data value from experimental arm group is generally bigger than the control arm group. 
